# Generated by Django 5.0.4 on 2024-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cursor_coordinates', models.CharField(max_length=50)),
                ('image_data_source', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
